### ISSUE TITLE
Can't Verify Saleforce Connection

### ISSUE THREAD

**Issue by chirino** [syndesisio/syndesis-verifier#12]
See:
<img width="841" alt="syndesis" src="https://user-images.githubusercontent.com/103255/26931928-10aa18fe-4c30-11e7-82ec-7c486c34f5ba.png">

**Comment by rhuss** [comment]
Think we already had that before. will check it later again.

**Comment by chirino** [comment]
@zregvart @rhuss any updates?

**Comment by zregvart** [comment]
@chirino @rhuss I've created a PR, seems to be OK for me (tested with `curl`), but I think that this uncovers a deeper issue: the connector name is not passed on to the verifier (the verifier uses a fixed connector name), and when considering that connectors can provide some of the options (and probably most will) this might be an issue going forward. Not sure if it's a UI, REST or conceptual issue, but I'm leaning towards the latter.

**Comment by rhuss** [comment]
The mismatch is laid out in https://github.com/syndesisio/syndesis-rest/issues/219, too. The problem is that when we create a _Syndesis Connection_ we have no action yet and hence cannot select a specific _Camel Connector_. Actually the idea is that we are taking an opinionated approach and choose one of the connectors as the "verifying connector" with the assumption that all connectors in the same 'family' can be verified the same way.

**Comment by zregvart** [comment]
This works nicely now.
